version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py load_jkuat_data &&
             python manage.py collectstatic --noinput &&
             gunicorn productivity_app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://user:pass@db:5432/productivity_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=productivity_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A productivity_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://user:pass@db:5432/productivity_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A productivity_app beat --loglevel=info
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - DATABASE_URL=postgres://user:pass@db:5432/productivity_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume: