# Generated by Django 5.2.6 on 2025-10-22 21:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFocus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote', models.TextField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('morning_routine', '🌅 Morning Routine'), ('fitness', '💪 Fitness'), ('meal', '🍽️ Meal'), ('academic', '📚 Academic'), ('personal', '🚀 Personal Development'), ('social', '❤️ Social'), ('reflection', '📊 Reflection'), ('rest', '😴 Rest')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Focus Quotes',
                'db_table': 'daily_focus',
            },
        ),
        migrations.AddField(
            model_name='progresstracker',
            name='consistency_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_time',
            field=models.TimeField(default='23:30:00'),
        ),
        migrations.CreateModel(
            name='SmartActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('morning_routine', '🌅 Morning Routine'), ('fitness', '💪 Fitness'), ('meal', '🍽️ Meal'), ('academic', '📚 Academic'), ('personal', '🚀 Personal Development'), ('social', '❤️ Social'), ('reflection', '📊 Reflection'), ('rest', '😴 Rest')], max_length=20)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('daily', 'Daily')], default='daily', max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(help_text='Activity duration in minutes')),
                ('priority_level', models.IntegerField(choices=[(1, 'Fixed - Cannot Move'), (2, 'High Priority'), (3, 'Medium Priority'), (4, 'Flexible')], default=3)),
                ('is_flexible', models.BooleanField(default=True)),
                ('shift_margin_minutes', models.IntegerField(default=30, help_text='How many minutes this activity can shift')),
                ('min_duration_minutes', models.IntegerField(default=15, help_text='Minimum duration required')),
                ('original_start_time', models.TimeField(blank=True, null=True)),
                ('last_adjusted', models.DateTimeField(blank=True, null=True)),
                ('adjustment_count', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'smart_activities',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
