# Generated by Django 5.2.6 on 2025-10-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dailyfocus_progresstracker_consistency_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityresource',
            name='icon',
            field=models.CharField(default='🔗', max_length=10),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7),
        ),
        migrations.AddField(
            model_name='resourcecategory',
            name='icon',
            field=models.CharField(default='📁', max_length=10),
        ),
    ]
